# <span style="color:rgb(160,0,86)">Datenmanipulation mit Python</span>

***

## <span style="color:rgb(160,0,86)">Lernziele</span>

- Sie wissen was eine **statistische Einheit** ist und können ihre Merkmale bezüglich ihrer **Ausprägungen** unterscheiden.
- Sie kennen die Python **Module** ***numpy*** und ***pandas***.  
- Sie können Daten **laden** und **einfache Operationen** ausführen.  

***

### <span style="color:rgb(160,0,86)">Was ist eine statistische Einheit?</span>

- Eine **statistische Einheit** ist Träger von Informationen und Eigenschaften, die für eine statistische Untersuchung von Interesse ist.
- Eine Eigenschaft einer statistischen Einheit, die von Interesse ist, heisst **statistisches Merkmal**.

#### <span style="color:rgb(160,0,86)">Beispiele:</span>

- In einer Notenstatistik für das Modul ASTAT ist jede Studentin und jeder Student des Moduls eine statistische Einheit. Das statistische Merkmal ist die Abschlussnote an der MEP.
- In einer schweizer Unfallstatistik im Jahr 2024 ist jeder Verkehrsunfall auf schweizer Strassen in diesem Jahr eine statistische Einheit. Statistische Merkmale können zum Beispiel Anzahl Todesopfer, Unfallkosten, Unfallstelle etc. sein.

***

### <span style="color:rgb(160,0,86)">Welche Typen von Merkmalen gibt es?</span>

- **Nominale Merkmale**: Die Ausprägungen des Merkmals können lediglich auf *Gleichheit* ($=$) oder *Ungleichheit* ($\neq$) untersucht werden. <br> Zum Beispiel das Geschlecht, die Nationalität oder der Beruf einer Person.
- **Ordinale Merkmale**: Die Ausprägungen des Merkmals haben zu der *Gleichheit* und *Ungleichheit* eine natürliche *Reihenfolge* ($>$, $<$). <br> Zum Beispiel das Gesamtprädikat eines Hochschulabschlusses mit den Auspägungen *ungenügend*, *genügend*, *befriedigend*, *gut*, *sehr gut* und *ausgezeichnet*. 
- **Metrische Merkmale**: Die Ausprägungen des Merkmals sind Zahlen. Neben dem Betrachen von *Gleichheit*, *Ungleichheit* und *Reihenfolge* kann mit diesen Ausprägungen auch *gerechnet* werden ($+\;$, $\,-\;$, $\,\cdot\;$, $\,/\;$ usw.). <br> Zum Beispiel die Temperatur (beliebige reelle Zahlen), der Umsatz (gerundete nicht negative reelle Zahlen), die Anzahl Mausklicks (nicht negative ganze Zahlen).

### <span style="color:rgb(160,0,86)">Wie werden statistische Einheiten zusammengefasst?</span>

Häufig werden statistische Einheiten mit ihren Merkmalen in einem rechteckigen Schema (einer Matrix, einer Tabelle) zusammengefasst. Die Einheiten werden über die Zeilen und ihre Merkmale in den Spalten erfasst. Zum Beispiel: 

$$\begin{bmatrix}
\text{Anna}&1981&w&176\\
\text{Beat}&2005&m&181\\
\text{Cary}&2011& &169\\
\text{Dana}&1991&w&165\\
\text{Edin}&1964&m&194
\end{bmatrix}$$

### <span style="color:rgb(160,0,86)">Sind Listen in Python eine passende Datenstruktur?</span>

Wir definieren zwei Listen:

In [56]:
Person_1 = [5.0,5.0,5.5]
Person_2 = [4.5,4.0,4.5]

Die Summe $+$ hängt die zwei Listen zusammen (Konkatenation).

In [57]:
Person_1 + Person_2

[5.0, 5.0, 5.5, 4.5, 4.0, 4.5]

Das Produkt $\,\ast\,$ liefert eine Fehlermeldung.

In [58]:
Person_1 * Person_2

TypeError: can't multiply sequence by non-int of type 'list'

Nein, mit **NumPy** (Numerical Python) geht das besser! Das NumPy-Modul bietet eine Sammlung mathematischer Operationen für mehrdimensionale Arrays.

- Mit dem Befehl $\;\mathtt{import}\;\mathtt{ModulName}\;$ können wir ganze Module in das Programm laden und mit dem **Punktoperator** $\;\cdot\;$ Attribute, Funktionen und Methoden aufrufen. Zum Beispiel $$\mathtt{numpy.array([1,2,3])}$$
- Oft ist es übersichtlicher, wenn wir mit dem Befehl $\;\mathtt{as}\; \mathtt{Kurzname}\;$ dem Modul ein Alias zuweisen. Dann können wir Attribute, Funktionen und Methoden über dieses Alias aufrufen. Zum Beispiel $$\mathtt{np.array([1,2,3])}$$

Wir machen aus den Listen **numpy arrays**:

In [ ]:
# pip install numpy
import numpy as np
P_1 = np.array(Person_1)
P_2 = np.array(Person_2)

Nun können wir **elementweise** rechnen:

In [ ]:
(P_1 + P_2)/2

array([4.75, 4.5 , 5.  ])

Aus verschachtelten Listen entstehen **zwei dimensionale Arrays**:

In [ ]:
Noten = np.array([P_1,P_2])
Noten

array([[5. , 5. , 5.5],
       [4.5, 4. , 4.5]])

Mit dem **Attribut** $\,\mathtt{shape}\,$ können wir die Anzahl **Zeilen** und **Spalten** als Paar ausgeben:

In [ ]:
Noten.shape

(2, 3)

Oder mit dem **Indexoperator** $\pmb{[\;\;]}$ direkt die Anzahl **Zeilen** bzw. die **Spalten**:

In [ ]:
print("Anzahl Zeilen:",Noten.shape[0])
print("Anzahl Spalten:",Noten.shape[1])

Anzahl Zeilen: 2
Anzahl Spalten: 3

Mit dem **Indexoperator** können wir auch ein Elemente im Array ausgeben:

In [ ]:
Noten[0,2]

np.float64(5.5)

Mit der **Slicing-Operation** $\pmb{[\;,\;]}$ können wir einen Teil im Array ausschneiden:

In [ ]:
Noten[:,:] # 2. Zeile

array([[5. , 5. , 5.5],
       [4.5, 4. , 4.5]])

In [ ]:
Noten[:,2] # 3. Spalte

array([5.5, 4.5])

In [ ]:
Noten[0:2,1:3] # 1. und 2. Zeile mit 2. und 3. Spalte

array([[5. , 5.5],
       [4. , 4.5]])

Für numpy Arrays gibt es viele **Methoden** $\;\mathtt{methodenName()}\;$, die mit dem **Punkt-Operator** $\pmb{\;\cdot\;}$ aufgerufen werden:

In [ ]:
Noten[0,:].max()

np.float64(5.5)

In [ ]:
Noten[:,2].min()

np.float64(4.5)

In [ ]:
Noten[1,:].sum()

In [ ]:
Noten.min()

In [ ]:
Noten.sum()

In [ ]:
Noten.mean()

Mit dem **Parameter** $\;\mathtt{axis}\;$ können wir angeben, ob die Methode entlang der Spalten (Wert 0) oder entlang der Zeilen (Wert 1) angewendet werden soll:

In [ ]:
Noten.sum(axis=0)

array([ 9.5,  9. , 10. ])

In [ ]:
Noten.sum(axis=1)

array([15.5, 13. ])

In [ ]:
Noten.mean(axis=0)

array([4.75, 4.5 , 5.  ])

In [ ]:
Noten.mean(axis=1)

array([5.16666667, 4.33333333])

Mit der numpy **Funktion** $\;\mathtt{unique}\;$ können wir ausgeben, was für Elemente im Array vorhanden sind. Der Array-Elemente werden in einem eindimensionalen Array ohne Dublikate zurückgegeben:

In [ ]:
np.unique(Noten)

array([4. , 4.5, 5. , 5.5])

Wenn wir zusätzlich dem Parameter $\;\mathtt{return\_counts}\;$ den Wert $\;\mathtt{True}\;$ zuweisen, erhalten wir in einem weiteren Array die Angaben, wie oft die entsprechenden Elemente vorkommen:

In [ ]:
np.unique(Noten,return_counts=True)

Wenn wir in der **Funktion** $\;\mathtt{unique}\;$ auch noch den Parameter $\;\mathtt{axis}\;$ auf 0 bzw. 1 setzen, können wir alle unterschiedlichen Zeilen bzw. alle Spalten ausgeben:

In [ ]:
Noten

In [ ]:
np.unique(Noten,axis=0)

array([[4.5, 4. , 4.5],
       [5. , 5. , 5.5]])

In [ ]:
np.unique(Noten,axis=1)

array([[5. , 5. , 5.5],
       [4. , 4.5, 4.5]])

Mit den Parameter $\;\mathtt{return\_counts}\;$ wird dann auch noch zurückgegeben, wie oft die Zeilen bzw. Spalten vorkommen.

Damit wir das demonstrieren können, machen wir zuerst einen grösseren Array:

In [ ]:
marks = np.array([Person_1,Person_1,Person_1,Person_2,Person_2,np.array([4,4.5,4.5])])
marks

array([[5. , 5. , 5.5],
       [5. , 5. , 5.5],
       [5. , 5. , 5.5],
       [4.5, 4. , 4.5],
       [4.5, 4. , 4.5],
       [4. , 4.5, 4.5]])

In [ ]:
np.unique(marks,return_counts=True,axis=0)

(array([[4. , 4.5, 4.5],
        [4.5, 4. , 4.5],
        [5. , 5. , 5.5]]),
 array([1, 2, 3]))

In [ ]:
np.unique(marks,return_counts=True,axis=1)

### <span style="color:rgb(160,0,86)">Wie können grosse Datenmengen verarbeitet werden?</span>

Häufige Formate für Daten in Matrix-Form sind:

- **csv**-Dateien (Tabulator-,Komma- oder Spalten getrennte Textdateien)
- **ods**-, **xls**-, **xlsx**-, **mdb**-Dateien (Tabellendokumente)
- **sav**-Dateien für SPSS
- **dta**-Dateien für STATA

**Pandas** (Panel Data) ist ein Python-Modul, das schnelle und flexible Datenstrukturen bereitstellt, die das Arbeiten mit Daten in Matrix-Form einfach und intuitiv macht.

#### <span style="color:rgb(160,0,86)">Beispiel:</span>

Wir wollen die folgenden Daten mit Pandas verarbeiten:

$$\begin{bmatrix}
\text{Greater London}&8663300&1572\\
\text{Tokyo}&9272565&627\\
\text{Paris}&2229621&105\\
\text{New York}&8491079&784\\
\end{bmatrix}$$

Zuerste definieren wir drei Arrays mit den Werten der Spalten:

In [ ]:
names = ["Greater London","Tokyo","Paris","New York"]
population = [8663300,9272565,2229621,8491079]
area = [1572,627,105,784]

Nun laden wir das Modul $\;\mathtt{pandas}\;$ unter dem Alias
$\;\mathtt{pd}\;$:

In [ ]:
# pip install pandas
import pandas as pd

Mit der $\;\mathtt{pandas}\;$ Funktion $\;\mathtt{DataFrame}\;$ können wir die drei Spalten zu einem **Datenrahmen** (eine zweidimensionale, tabellarische Datenstruktur) zusammenfassen:

In [ ]:
df = pd.DataFrame({"cities":names,"population":population,"area":area})
df

           cities  population  area
0  Greater London     8663300  1572
1           Tokyo     9272565   627
2           Paris     2229621   105
3        New York     8491079   784

Mit den Methoden $\;\mathtt{head()}\;$ bzw. $\;\mathtt{tail()}\;$ können wir den Anfang bzw. das Ende des Datenrahmens anzeigen:

In [ ]:
df.head(2)

                population  area   pop_density
cities
Greater London     8663300  1572   5511.005089
Tokyo              9272565   627  14788.779904

In [ ]:
df.tail(2)

     cities  population  area
2     Paris     2229621   105
3  New York     8491079   784

Auch die $\;\mathtt{DataFrame}\;$ Objekte haben das Attribut $\;\mathtt{shape}\,$:

In [ ]:
df.shape

(4, 3)

Die Namen der Spalten können wir mit dem Attribut $\;\mathtt{columns}\;$ ausgeben:

In [ ]:
df.columns

Index(['cities', 'population', 'area'], dtype='object')

Über die **Namen der Spalten** und dem üblichen **Slicing** können wir Teile des Datenrahmens ausgeben:

In [ ]:
df[["population"]][2:4]

   population
2     2229621
3     8491079

In [ ]:
df[["cities","area"]][0:1]

           cities  area
0  Greater London  1572

Standardmässig werden die Zeilen mit einem **Index** numeriert. Wir können aber mit der Methode $\;\mathtt{set\_index()}\;$ einen eigenen Index setzen:

In [ ]:
df.set_index("cities")

Allerdings wird dieser Index im Datenrahmen **nicht fix** festgesetzt. Die Methode $\;\mathtt{set\_index()}\;$ wird nur für die einmalige Ausgabe angewendet:

In [ ]:
df

Erst wenn wir den Parameter $\;\mathtt{inplace}\;$ auf $\;\mathtt{True}\;$ setzen, bleibt der neue Index erhalten:

In [ ]:
df.set_index("cities",inplace=True)

In [ ]:
df

                population  area
cities
Greater London     8663300  1572
Tokyo              9272565   627
Paris              2229621   105
New York           8491079   784

Mit der Methode $\;\mathtt{loc}[\mathtt{Zeilen},\mathtt{Spalten}]\;$ können wir Zeilen und Spalten **anhand von Labels** (also den Indexwerten und Spaltennamen) auszuwählen:

In [ ]:
df.loc["Tokyo"] # Rückgabe ist ein Series

population    9272565
area              627
Name: Tokyo, dtype: int64

In [ ]:
df.loc[["Tokyo","Paris"]] # Rückkgabe ist ein DataFrame

        population  area
cities
Tokyo      9272565   627
Paris      2229621   105

In [ ]:
df.loc["Tokyo","population"] # Rückgabe ist ein int64

np.int64(9272565)

Über den Index-Operator können wir direkt neue Spalten erstellen:

In [ ]:
df["pop_density"] = df["population"]/df["area"]
df

                population  area   pop_density
cities
Greater London     8663300  1572   5511.005089
Tokyo              9272565   627  14788.779904
Paris              2229621   105  21234.485714
New York           8491079   784  10830.457908

Meistens werden wir die Daten nicht selbst als Arrays definieren und dann ein Datenrahmen über die Spalten und Spaltennamen aufbauen. Oft werden wir Daten aus eine Datei einlesen.

Mit der **Funktion** $\;\mathtt{read\_csv()}\;$ können wir zum Beispiel $\;\mathtt{csv}$-Dateien einlesen. Als **Argument** braucht diese Funktion den **Dateipfad als Zeichenkette**:

In [62]:
gla_cities = pd.read_csv("/Users/muellefa/repos/ASTAT/SW01/Daten/GLA_World_Cities_2016.csv")
gla_cities.head(3)

,City,Country,Population,Inland area in km2,Density in people per hectare,Dwellings,Density in dwellings per hectare,People per dwelling,Approx city radius km,Main topographical constraint,Constraint
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Greater London,England,"8,663,300","1,572",55.0,"3,454,490",22.0,2.5,23.0,Rivers,4%
2,Inner London,England,"3,439,700",319,108.0,"1,460,840",46.0,2.4,10.0,Rivers,5%

In [63]:
gla_cities.shape

(18, 11)

Wenn in einer Datei in Zeilen oder Spalten Werte fehlen (fehlende Werte = **Not Available**), können wir diese mit der Methode $\;\mathtt{dropna()}\;$ aus dem Datenrahmen löschen. 

Mit dem Parameter $\;\mathtt{how}\;$ können angeben, ob nur Zeilen bzw. Spalten gelöscht werden sollen, in denen alle Werte fehlen (Leerzeilen bzw. Leerspalten):
- "$\mathtt{any}$"$\;$: Löscht alle Zeilen/Spalten, die mindestens einen NaN-Wert enthalten
- "$\mathtt{all}$"$\;$ : Löscht nur Zeilen/Spalten, die nur aus NaN-Werten bestehen

In [64]:
gla_cities.dropna(how="all")

,City,Country,Population,Inland area in km2,Density in people per hectare,Dwellings,Density in dwellings per hectare,People per dwelling,Approx city radius km,Main topographical constraint,Constraint
1,Greater London,England,"8,663,300","1,572",55.0,"3,454,490",22.0,2.5,23.0,Rivers,4%
2,Inner London,England,"3,439,700",319,108.0,"1,460,840",46.0,2.4,10.0,Rivers,5%
3,Outer London,England,"5,223,500","1,254",42.0,"1,993,660",16.0,2.6,NaN,NaN,NaN
4,Paris,France,"2,229,621",105,212.0,"1,336,209",127.0,1.7,8.0,Rivers,2%
5,Lyon,France,"500,715",48,105.0,"265,599",55.0,1.9,7.0,Rivers,5%
6,Berlin,Germany,"3,469,849",892,39.0,"1,892,000",21.0,1.8,16.0,Rivers,6%
7,Madrid (City),Spain,"3,141,991",606,52.0,"1,320,531",22.0,2.4,13.0,Mountains,12%
8,Barcelona,Spain,"1,604,555",98,163.0,"684,078",70.0,2.3,6.0,Coast and mountains,75%
9,Sevilla,Spain,"693,878",141,49.0,"268,435",19.0,2.6,7.0,Rivers,3%
10,New York (City),United States,"8,491,079",784,108.0,"3,371,062",43.0,2.5,14.0,Coast and rivers,40%
11,Chicago,United States,"2,722,389",590,46.0,"1,194,337",20.0,2.3,13.0,Lake,45%
12,Boston,United States,"617,594",125,49.0,"272,481",22.0,2.3,6.0,Coast,30%
13,Rio de Janeiro (Municipality),Brazil,"6,476,631",1200,54.0,"2,467,000",21.0,2.6,18.0,Coast and mountains,75%
14,Belo Horizonte (Municipality),Brazil,"2,375,151",331,76.0,"762,075",23.0,3.1,10.0,Mountains,45%
15,Singapore,Singapore,"3,902,710",666,59.0,"1,225,300",18.0,3.2,14.0,Coast,95%
16,Tokyo (Special Wards Area),Japan,"9,272,565",627,148.0,"6,437,000",103.0,1.4,14.0,Coast and mountains,70%
17,Osaka (City),Japan,"2,691,742",225,120.0,"1,634,100",73.0,1.6,8.0,Coast,20%

In [65]:
gla_cities.shape

(18, 11)

Auch hier müssen wir den Parameter $\;\mathtt{inplace}\;$ auf $\;\mathtt{True}\;$ setzen, wenn wir die Zeilen bzw. Spalten fix löschen wollen:

In [66]:
gla_cities.dropna(how="all",inplace=True)

In [67]:
gla_cities.shape

(17, 11)

Die Namen der Spalten können wir mit der Methode $\;\mathtt{rename()}\;$ ändern:

In [68]:
gla_cities.columns

Index(['City', 'Country', 'Population', 'Inland area in km2',
       'Density in people per hectare', 'Dwellings',
       'Density in dwellings per hectare', 'People per dwelling',
       'Approx city radius km', 'Main topographical constraint', 'Constraint'],
      dtype='object')

In [69]:
renamecols = {"Inland area in km2":"Area km2"}
gla_cities.rename(columns=renamecols,inplace=True)
gla_cities.columns

Index(['City', 'Country', 'Population', 'Area km2',
       'Density in people per hectare', 'Dwellings',
       'Density in dwellings per hectare', 'People per dwelling',
       'Approx city radius km', 'Main topographical constraint', 'Constraint'],
      dtype='object')

Nun ergänzen wir im Datenrahmen eine Spalten ***pop_density*** für die Populationsdichte:

In [71]:
gla_cities["pop_density"] = gla_cities["Population"]/gla_cities["Area km2"]

TypeError: unsupported operand type(s) for /: 'str' and 'str'

Dabei entsteht eine Fehlermeldung, weil die Werte in den Spalten ***Population*** und ***Area km2*** Zeichenketten sind.
- Den Tausenderstrich $\,\pmb{,}\,$ können wir mit der Methode $\;\mathtt{str.replace()}\;$ durch eine leere Zeichenkette ersetzen
- Den Typ String können wir mit der Methode $\;\mathtt{astype()}\;$ in eine Kommazahl umwandeln

In [72]:
gla_cities["Population"] = gla_cities["Population"].str.replace(",","").astype(float)
gla_cities.head(3)

,City,Country,Population,Area km2,Density in people per hectare,Dwellings,Density in dwellings per hectare,People per dwelling,Approx city radius km,Main topographical constraint,Constraint
1,Greater London,England,8663300.0,"1,572",55.0,"3,454,490",22.0,2.5,23.0,Rivers,4%
2,Inner London,England,3439700.0,319,108.0,"1,460,840",46.0,2.4,10.0,Rivers,5%
3,Outer London,England,5223500.0,"1,254",42.0,"1,993,660",16.0,2.6,NaN,NaN,NaN

In [73]:
gla_cities["Area km2"] = gla_cities["Area km2"].str.replace(",","").astype(float)
gla_cities["Dwellings"] = gla_cities["Dwellings"].str.replace(",","").astype(float)

In [74]:
gla_cities["pop_density"] = gla_cities["Population"]/gla_cities["Area km2"]
gla_cities["pop_density"].head(3)

1     5511.005089
2    10782.758621
3     4165.470494
Name: pop_density, dtype: float64

Oft ist es auch sinnvoll Werte in eine besser geeignete Einheit umzurechen:

In [75]:
gla_cities["Population (M)"] = gla_cities["Population"]/1000000 
gla_cities.head(3)

,City,Country,Population,Area km2,Density in people per hectare,Dwellings,Density in dwellings per hectare,People per dwelling,Approx city radius km,Main topographical constraint,Constraint,pop_density,Population (M)
1,Greater London,England,8663300.0,1572.0,55.0,3454490.0,22.0,2.5,23.0,Rivers,4%,5511.005089,8.6633
2,Inner London,England,3439700.0,319.0,108.0,1460840.0,46.0,2.4,10.0,Rivers,5%,10782.758621,3.4397
3,Outer London,England,5223500.0,1254.0,42.0,1993660.0,16.0,2.6,NaN,NaN,NaN,4165.470494,5.2235

Mit der Methode $\;\mathtt{apply()}\;$ können wir bestehende oder selbst definierte Funktion auf die Werte einer Spalte anwenden:

In [76]:
def city_size(x):
    if x < 1.5:
        s = "Small"
    elif 1.5 <= x < 3:
        s = "Medium"
    elif 3 <= x < 5:
        s = "Large"
    else:
        s = "Mega"
    return s
city_size(2.3)

'Medium'

In [77]:
gla_cities["City Size"] = gla_cities["Population (M)"].apply(city_size)
gla_cities.head(3)

,City,Country,Population,Area km2,Density in people per hectare,Dwellings,Density in dwellings per hectare,People per dwelling,Approx city radius km,Main topographical constraint,Constraint,pop_density,Population (M),City Size
1,Greater London,England,8663300.0,1572.0,55.0,3454490.0,22.0,2.5,23.0,Rivers,4%,5511.005089,8.6633,Mega
2,Inner London,England,3439700.0,319.0,108.0,1460840.0,46.0,2.4,10.0,Rivers,5%,10782.758621,3.4397,Large
3,Outer London,England,5223500.0,1254.0,42.0,1993660.0,16.0,2.6,NaN,NaN,NaN,4165.470494,5.2235,Mega

Mit der Syntax $\;\mathtt{dataFrame}[\mathtt{Bedingung}]\;$ können Zeilen im Datenrahmen **filtern**:

In [78]:
gla_cities[gla_cities["City Size"]=="Small"]

,City,Country,Population,Area km2,Density in people per hectare,Dwellings,Density in dwellings per hectare,People per dwelling,Approx city radius km,Main topographical constraint,Constraint,pop_density,Population (M),City Size
5,Lyon,France,500715.0,48.0,105.0,265599.0,55.0,1.9,7.0,Rivers,5%,10431.562500,0.500715,Small
9,Sevilla,Spain,693878.0,141.0,49.0,268435.0,19.0,2.6,7.0,Rivers,3%,4921.120567,0.693878,Small
12,Boston,United States,617594.0,125.0,49.0,272481.0,22.0,2.3,6.0,Coast,30%,4940.752000,0.617594,Small

Auch die Kombination von **Spaltenwahl und Zeilenfiltern** in einer Zeile ist möglich:

In [79]:
gla_cities[["City","Population (M)"]][gla_cities["Population (M)"]>8]

                           City  Population (M)
1               Greater London         8.663300
10             New York (City)         8.491079
16  Tokyo (Special Wards Area)         9.272565

Mit der Methode $\;\mathtt{groupby()}\;$ können wir einen Datenrahmen über die Werte einer Spalte **gruppieren** und dann in den Gruppen eine Anwendung auf die Werte ausführen:

In [80]:
gla_grouped = gla_cities.groupby("City Size")
gla_grouped.size() # Grösse der Gruppen

City Size
Large     4
Medium    5
Mega      5
Small     3
dtype: int64

In [81]:
gla_grouped["Population (M)"].mean() # Mittelwerte der Gruppen

City Size
Large     3.488563
Medium    2.324692
Mega      7.625415
Small     0.604062
Name: Population (M), dtype: float64

In [ ]:
gla_grouped["Population (M)"].min() # Kleinste Werte in den Gruppen

### <span style="color:rgb(160,0,86)">Aufgabe 1</span>

Diese Aufgabe befasst wir uns mit dem Datensatz **weather.csv** im Ordner Daten.

- Laden Sie den Datensatz und speichern Sie diesen unter der Variable **data**.
- Wählen Sie den Wert der zweiten Zeile und dritten Spalte aus.
- Wählen Sie die 4. Zeile aus.
- Wählen Sie die 1. und die 4. Spalte aus.
- Ersetzen Sie den Spaltennamen Basel durch Genf.
- Bestimmen Sie die mittleren Temperaturen aller Städte.
- Bestimmen Sie die mittleren Temperaturen aller Monate.
- Ergänzen Sie eine Spalte mit den mittleren monatlichen Temperaturen.

***

### <span style="color:rgb(160,0,86)">Lösungsvorschlag</span>

**Teilaufgabe:**
- Laden Sie den Datensatz und speichern Sie diesen unter der Variable **data**.

In [ ]:
import pandas as pd
import numpy as np

data = pd.read_csv("Daten/weather.csv")

In [ ]:
data.shape # Testen, ob die Daten gelesen wurden

(6, 5)

***

**Teilaufgabe:**
- Wählen Sie den Wert der zweiten Zeile und dritten Spalte aus.

In [ ]:
# Was sind die Namen der Spalten?
data.columns

Index(['Luzern', 'Basel', 'Chur', 'Zurich'], dtype='object')

In [ ]:
# Was sind die Namen der Zeilen
data.index

Index(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'], dtype='object')

In [ ]:
data.loc["Feb","Chur"] # Zugriff über die Namen

1

In [ ]:
data.iloc[1,2] # Zugriff über die Nummern

1

***

**Teilaufgabe:**
- Wählen Sie die 4. Zeile aus.

In [ ]:
data.loc[["Apr"],:] # Auswahl über den Namen

     Luzern  Genf  Chur  Zurich  Mittlere Temperatur
Apr      16    12    14      17                14.75

In [ ]:
data.iloc[[3],:] # Auswahl über die Nummer

     Luzern  Genf  Chur  Zurich  Mittlere Temperatur
Apr      16    12    14      17                14.75

***

**Teilaufgabe:**
- Wählen Sie die 1. und die 4. Spalte aus.

In [ ]:
data.loc[:,["Luzern","Zurich"]] # Auswahl über die Namen

     Luzern  Zurich
Jan       2       4
Feb       5       0
Mar      10       8
Apr      16      17
May      21      20
Jun      25      27

In [ ]:
data.iloc[:,[0,3]] # Auswahl über die Nummern

     Luzern  Zurich
Jan       2       4
Feb       5       0
Mar      10       8
Apr      16      17
May      21      20
Jun      25      27

***

**Teilaufgabe:**
- Ersetzen Sie den Spaltennamen Basel durch Genf.

In [ ]:
data.rename(columns={"Basel":"Genf"},inplace=True)
data.columns

Index(['Luzern', 'Genf', 'Chur', 'Zurich'], dtype='object')

***

**Teilaufgabe:**
- Bestimmen Sie die mittleren Temperaturen aller Städte.

In [ ]:
data.mean(axis=0)

Luzern    13.166667
Genf      13.000000
Chur      11.500000
Zurich    12.666667
dtype: float64

***

**Teilaufgabe:**
- Bestimmen Sie die mittleren Temperaturen aller Monate.

In [ ]:
data.mean(axis=1)

Jan     2.00
Feb     3.00
Mar    10.50
Apr    14.75
May    21.25
Jun    24.00
dtype: float64

***

**Teilaufgabe:**
- Ergänzen Sie eine Spalte mit den mittleren monatlichen Temperaturen.

In [ ]:
data["Mittlere Temperatur"] = data.mean(axis=1)
data.head(3)

     Luzern  Genf  Chur  Zurich  Mittlere Temperatur
Jan       2     5    -3       4                  2.0
Feb       5     6     1       0                  3.0
Mar      10    11    13       8                 10.5

***

### <span style="color:rgb(160,0,86)">Aufgabe 2</span>

Das Dataframe **d.fuel** im Ordner Daten enthält die Daten verschiedener Fahrzeuge aus einer amerikanischen Untersuchung der 80er-Jahre. Jede Zeile enthält die Daten eines
Fahrzeuges (ein Fahrzeug entspricht einer statistischen Einheit).

- Laden Sie das Dataframe.
- Beschreiben Sie die Ausprägung der Merkmale.
- Wählen Sie die fünfte Zeile des Dataframe aus. Welche Werte stehen in der fünften Zeile?
- Wählen Sie die erste bis fünfte Beobachtung des Dataframes aus.
- Zeigen Sie gleichzeitig die 1. bis 3. und die 57. bis 60. Beobachtung des Dataframes an.
- Berechnen Sie den Mittelwert der Reichweiten aller Autos in Miles/Gallon.
- Berechnen Sie den Mittelwert der Reichweiten der Autos 7 bis 22.
- Ergänzen Sie eine Spalte **t.kml**, die alle Reichweiten in km/l, und
eine Spalte **t.kg**, die alle Gewichte in kg enthält.
- Berechnen Sie den Mittelwert der Reichweiten in km/l und denjenigen der Fahrzeuggewichte in kg.
- Bestimmen Sie das mittlere Gewicht der Sportwagen (*Sporty*).

***

### <span style="color:rgb(160,0,86)">Lösungsvorschlag</span>

**Teilaufgabe:**
- Laden Sie das Dataframe.

In [ ]:
import pandas as pd
import numpy as np

df_fuel = pd.read_csv("Daten/d.fuel.dat")
df_fuel.shape # Testen, ob die Daten gelesen wurden

(60, 4)

***

**Teilaufgabe:**
- Beschreiben Sie die Ausprägung der Merkmale.

In [ ]:
df_fuel.head(3) # Was sind die Namen der Spalten (Merkmale)

   X  weight  mpg   type
0  1    2560   33  Small
1  2    2345   33  Small
2  3    1845   37  Small

In [ ]:
df_fuel.set_index("X",inplace=True) # Setze X als Index

In [ ]:
df_fuel.apply(np.unique)

weight    [1845, 1900, 2075, 2170, 2260, 2275, 2285, 229...
mpg       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 2...
type           [Compact, Large, Medium, Small, Sporty, Van]
dtype: object

Die Ausprägungen der Merkmale sind
- weight: **numerisch** (*eine nicht negative Zahl*)
- mpg: **numerisch** (*eine nicht negative Zahl*)
- type: **nominal** (*Compact*, *Large*, *Medium*, *Small*, *Sporty*, *Van*)

***

**Teilaufgabe:**
- Wählen Sie die fünfte Zeile des Dataframe aus. Welche Werte stehen in der fünften Zeile?

In [ ]:
df_fuel.loc[[5],:]

   weight  mpg   type
X
5    2440   32  Small

***

**Teilaufgabe:**
- Wählen Sie die erste bis fünfte Beobachtung des Dataframes aus.

In [ ]:
df_fuel.loc[[1,2,3,4,5],:]

   weight  mpg   type
X
1    2560   33  Small
2    2345   33  Small
3    1845   37  Small
4    2260   32  Small
5    2440   32  Small

***

**Teilaufgabe:**
- Zeigen Sie gleichzeitig die 1. bis 3. und die 57. bis 60. Beobachtung des Dataframes an.

In [ ]:
df_fuel.loc[[1,2,3,57,58,59,60],:]

    weight  mpg   type
X
1     2560   33  Small
2     2345   33  Small
3     1845   37  Small
57    3735   19    Van
58    3415   20    Van
59    3185   20    Van
60    3690   19    Van

***

**Teilaufgabe:**
- Berechnen Sie den Mittelwert der Reichweiten aller Autos in Miles/Gallon.

In [ ]:
df_fuel.loc[:,"mpg"].mean()

24.583333333333332

***

**Teilaufgabe:**
- Berechnen Sie den Mittelwert der Reichweiten der Autos 7 bis 22.

In [ ]:
df_fuel.loc[7:22,"mpg"].mean()

27.75

***

**Teilaufgabe:**
- Ergänzen Sie eine Spalte **t.kml**, die alle Reichweiten in km/l, und
eine Spalte **t.kg**, die alle Gewichte in kg enthält.

Für die amerikanischen Einheiten gelten:
- Ein **Pound** entspricht **0.453592 Kilogramm**
- Eine **Gallone** entspricht **3.78541 Liter**
- Eine **Meile** entspricht **1.60934 Kilometer**

Wenn ein Fahrzeut eine Reichweite von $x$ mpg hat, fährt es $x$ Meilen mit einer Gallone.<br>

Das heisst, es fährt $x\cdot 1.60934$ Kilometer mit einer Gallone.<br>

Also fährt das Fahrzeug $\displaystyle\frac{x\cdot 1.60934}{3.78541}$ Kilometer mit einem Liter.

In [ ]:
df_fuel["t.kml"] = df_fuel["mpg"] * 1.60934 / 3.78541
df_fuel["t.kg"]  = df_fuel["weight"] * 0.453592
df_fuel.head(3)

   weight  mpg   type      t.kml        t.kg
X
1    2560   33  Small  14.029714  1161.19552
2    2345   33  Small  14.029714  1063.67324
3    1845   37  Small  15.730285   836.87724

***

**Teilaufgabe:**
- Berechnen Sie den Mittelwert der Reichweiten in km/l und denjenigen der Fahrzeuggewichte in kg.

In [ ]:
df_fuel.loc[:,["t.kml","t.kg"]].mean()

t.kml      10.451428
t.kg     1315.794793
dtype: float64

***

**Teilaufgabe:**
- Bestimmen Sie das mittlere Gewicht der Sportwagen (*Sporty*).

In [ ]:
df_fuel[["t.kml","t.kg"]][df_fuel.loc[:,"type"]=="Sporty"].mean(axis=0)

t.kml      11.053714
t.kg     1269.553609
dtype: float64

![HSLU](Bilder/LogoHSLU.png)